INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ShowBatteries

ShowBatteries_FILES = Tweak.xm
ShowBatteries_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
