INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AmericanBudget

AmericanBudget_FILES = Tweak.x
AmericanBudget_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
