INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = PopupOnStart

PopupOnStart_FILES = Tweak.x
PopupOnStart_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
